routes/api_html.py
from flask import Blueprint, render_template, redirect, url_for

from db import db
from models import Customer, Product, Order

# Creates a Blueprint object (similar to Flask). Make sure you give it a name!
api_html_bp = Blueprint("api_html", __name__)


@api_html_bp.route('/home')
def home_message():
    return render_template('home.html', name='user')


@api_html_bp.route('/')
def home():
    return render_template('home.html')


@api_html_bp.route('/customers')
def customer():
    customers = Customer.query.all()
    return render_template('customers.html', customers=customers)


@api_html_bp.route('/products')
def product():
    products = Product.query.all()
    return render_template('products.html', products=products)


@api_html_bp.route("/orders")
def orders():
    orders = Order.query.all()
    return render_template('orders.html', orders=orders)


@api_html_bp.route("/customer/<int:customer_id>")
def customer_detail(customer_id):
    customer = Customer.query.get_or_404(customer_id)
    return render_template('customer_detail.html', customer=customer)


@api_html_bp.route("/order/<int:order_id>")
def order_detail(order_id):
    order = Order.query.get_or_404(order_id)
    return render_template('order_detail.html', order=order)


# Delete orders using post method, also uses url_for and redirect
@api_html_bp.route("/orders/<int:order_id>/delete", methods=["POST"])
def order_delete(order_id):
    order = db.get_or_404(Order, order_id)
    if order.processed:
        return "Cannot delete processed order", 400

    db.session.delete(order)
    db.session.commit()
    return redirect(url_for('api_html.orders'))


@api_html_bp.route("/orders/<int:order_id>/process", methods=["POST"])
def order_process(order_id):
    order = db.get_or_404(Order, order_id)
    if order.processed:
        return "Order already processed", 400

    success, message = order.process()
    if success:
        db.session.commit()
        return redirect(url_for('api_html.orders'))
    else:
        return message, 400

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <nav>
            <a href="/home">Homepage</a>
            <a href="/customers">customers</a>
            <a href="/products">products</a>
            <a href="/orders">orders</a>
        </nav>
        
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/customer_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Orders associated with this customer</h1>
{% for order in customer.orders %}
    <h2><a href="{{ url_for('api_html.order_detail', order_id=order.id) }}">Order #{{ order.id }}</a></h2>
{% endfor %}
{% endblock %}

templates/customers.html
{% extends "base.html" %}

{% block content %}
<h1>Customers</h1>
{% for customer in customers %}
<li>
    <span>{{ customer.name }}</span>
    <span>{{ customer.phone }}</span>
    <span>, Balance : ${{ customer.balance }}</span>
    <a href="{{ url_for('api_html.customer_detail', customer_id=customer.id) }}">View details</a>

</li>
{% endfor %}
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Flask Template Example</title>
</head>
<body>
    <nav>
        <a href="/home">Homepage</a>
        <a href="/customers">customers</a>
        <a href="/products">products</a>
        <a href="/orders">orders</a>
    </nav>
    <h1>Hello, {{ name }}!</h1>
    <ul>
        {% for element in my_list %}
            <li>List element: {{ element }}<li></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/order_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Order #{{ order.id }}</h1>
<h2>Items</h2>
{% for item in order.items %}
    <p>{{ item.product.name }}, Quantity:{{ item.quantity }}</p>
{% endfor %}
<h2>Total</h2>
<p>${{ order.total }}</p>
    <form method="POST" action="{{ url_for('api_html.order_delete', order_id=order.id) }}">
        <button type="submit">Delete</button>
    </form>
    <form method="POST" action="{{ url_for('api_html.order_process', order_id=order.id) }}">
        <button type="submit">Process</button>
    </form>
{% endblock %}

templates/orders.html
{% extends "base.html" %}

{% block content %}
<h1>Orders</h1>
{% for order in orders %}
    {% set class_name = "pending" %}
    {% if order.processed %}
        {% set class_name = "processed" %}
    {% endif %}
    <p class="{{ class_name }}">{{ order.id }} {{ order.customer.name }}, Status:{{ class_name }}</p>
    <a href="{{ url_for('api_html.order_detail', order_id=order.id) }}">View details</a>
{% endfor %}
{% endblock %}

templates/products.html
{% extends "base.html" %}

{% block content %}
<h1>Products</h1>
{% for product in products %}
<li>
    <span>{{ product.name }}, </span>
    <span>Price: ${{ product.price }}, </span>
    <span>Quantity: {{ product.available }}</span>
</li>
{% endfor %}
{% endblock %}